name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
        if: ${{ !env.ACT }}
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis
      
      - uses: actions/checkout@v4
        if: ${{ env.ACT }}
      
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        with:
          pr-mode: false
          args: 
            '--compile-commands=./qodana/compile_commands.json'
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
